config/routes.rb
IGame::Application.routes.draw do

  get "pages/dashboard"

  resources :games do
    resources :game_comments
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  
  get "sessions/new"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"
  resources :sessions
  resources :users do
    resources :played_relationships
  end
  resources :played_relationships, only: [:create, :destroy]

  get "weibo" => "weibo#connect", :as => "weibo"
  patch "post_weibo" => "weibo#post", :as => "post_weibo"

  get "callback" => "weibo#callback"

  

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :played_relationships, foreign_key: "game_id"
  has_many :users, :through => :played_relationships

  has_many :game_comments

  #has_attached_file :game_cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  mount_uploader :game_coverpicture, GameCoverUploader
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    #render params.inspect
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :game_coverpicture)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def game_title(id)
    a = Game.find_by_id(id)
    a.name
  end
end

app/views/games/_form.html.erb
<%= form_for(@game, :html => {:multipart => true}) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


    <div class="field">

        <%= f.file_field :game_coverpicture %>

      </div>

    <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>


<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>


<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.name, game %></td>
        <td><%= game.description %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Game', new_game_path, :class=>"btn btn-success", :method => "get" %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>


<%= link_to 'Back', games_path %>

    </div>

app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <%= image_tag(@game.game_coverpicture_url, :width => 600) if @game.game_coverpicture.present? %>
  <%= @game.game_coverpicture %>
</p>

<%= form_for @game, {:url => post_weibo_path } do |f| %>
<!--<%= button_to "Share", post_weibo_path %>-->
    <%= f.hidden_field :name %>
    <%= f.submit "OK" %>
<% end %>


<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Edit
</button>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<br/>
<br/>

<% if current_user %>

<% if !current_user.played_relationships.find_by_game_id(@game.id) %>

    <%= form_for(current_user.played_relationships.build(game_id: @game.id) ) do |f| %>
        <div><%= f.hidden_field :game_id %></div>
        <%= f.submit "Played!", class: "btn btn-primary" %>
    <% end %>
<% end %>



<% if current_user.played_relationships.find_by_game_id(@game.id) %>
    <%= form_for [current_user, current_user.played_relationships.find_by_game_id(@game.id)], html:{method: :delete} do |f| %>
        <div><%= f.hidden_field :game_id %></div>
        <p>
          <%= f.submit "UnPlayed!", class: "btn btn-primary" %>
    <% end %>
<% end %>


<% end %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>


<h2>Comments</h2>
<% @game.game_comments.each do |comment| %>
      <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
     
      <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
<% end %>


<h2>Add a comment:</h2>
<%= form_for ([@game, @game.game_comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %>:
      <%= f.label current_user.nickname%>
    </p>

      <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
      <p>
      <%= f.submit %>
    </p>
<% end %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'igame-web'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>