config/routes.rb
IGame::Application.routes.draw do

  get "pages/dashboard"

  resources :games do
    resources :game_comments
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  
  get "sessions/new"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"
  resources :sessions
  resources :users do
    resources :played_relationships
  end
  resources :played_relationships, only: [:create, :destroy]

  get "weibo" => "weibo#connect", :as => "weibo"
  patch "post_weibo" => "weibo#post", :as => "post_weibo"

  get "callback" => "weibo#callback"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IGame</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <nav class=" navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">iGame</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><%= link_to "Games", games_path %></li>
        <%
           WeiboOAuth2::Config.api_key = '2995749339';
           WeiboOAuth2::Config.api_secret = '8935c930b08d4f96fabcce32474a250a';
           WeiboOAuth2::Config.redirect_uri = 'http://vast-coast-4942.herokuapp.com/callback'
           client = WeiboOAuth2::Client.new
           if session[:access_token] && !client.authorized?
             token = client.get_token_from_hash({:access_token => session[:access_token], :expires_at => session[:expires_at]})
             if token.validated?
        %>
            <li><%= link_to "Weibo已连接", weibo_path %></li>


                <% end %>
        <% else %>
            <li><%= link_to "连接到Weibo", weibo_path %></li>
            <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li>-->


          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
              <li><a href="/pages/dashboard">Logged in as <%= current_user.email %></a></li>
              <li><%= link_to "Log out", log_out_path %></li>
            </ul>
          <% else %>
              <li><%= link_to "Sign up", sign_up_path %></li>
              <li><%= link_to "log in", log_in_path %></li>
          <% end %>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

</head>


<body>






	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/batman.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I Game</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "i_game" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div data-yield="main"></div>

<script type="text/javascript">
  IGame.run();
</script>

</body>
</html>